Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@MohammedSaifullah9 
MohammedSaifullah9
/
powerplatform-actions-lab
Public
forked from microsoft/powerplatform-actions-lab
Code
Pull requests
Actions
Projects
Security
Insights
Settings
powerplatform-actions-lab/.github/workflows/export-and-branch-solution.yml
@MohammedSaifullah9
MohammedSaifullah9 Update export-and-branch-solution.yml
…
Latest commit 1933cd5 4 hours ago
 History
 2 contributors
@davidjenni@MohammedSaifullah9
53 lines (46 sloc)  1.58 KB

name: Export-Unpack-Checkin2
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://orga13a6c11.crm.dynamics.com/'
        user-name: 'admin@CRM063646.onmicrosoft.com'
        password-secret: ${{ secrets.password }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://orga13a6c11.crm.dynamics.com/'
        user-name: 'admin@CRM063646.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: CICDGitHub
        solution-output-file: out/exported/CICDGITHub.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/CICDGITHub.zip
        solution-folder: out/solutions/ALMLab
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/ALMLab
        solution-target-folder: solutions/ALMLab
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
powerplatform-actions-lab/export-and-branch-solution.yml at ALMLab-20221206-1346 · MohammedSaifullah9/powerplatform-actions-lab
